
api = "https://api.kvk.nl/test/api/v1/basisprofiel"
apiKey = "apikey: l7xx1f2691f2520d487b902f4e0b57a0b197"



{"pagina":1,"resultatenPerPagina":10,"totaal":10,"resultaten":[{"kvkNummer":"68750110","vestigingsnummer":"000037178601","naam":"Test BV Donald Nevenvestiging",
"adres":{"binnenlandsAdres":{"type":"bezoekadres","straatnaam":"Brinkerinckbaan","plaats":"Diepenveen"}},"type":"nevenvestiging",
"links":[{"rel":"basisprofiel","href":"https://api.kvk.nl/test/api/v1/basisprofielen/68750110"},{"rel":"vestigingsprofiel","href":"https://api.kvk.nl/test/api/v1/vestigingsprofielen/000037178601"}]},
{"kvkNummer":"69599076","vestigingsnummer":"000038509490","naam":"Test VOF Guus de 2e","adres":{"binnenlandsAdres":{"type":"bezoekadres","straatnaam":"Anjerhof","plaats":"Aalsmeer"}},"type":"nevenvestiging",
"links":[{"rel":"basisprofiel","href":"https://api.kvk.nl/test/api/v1/basisprofielen/69599076"},{"rel":"vestigingsprofiel","href":"https://api.kvk.nl/test/api/v1/vestigingsprofielen/000038509490"}]},
{"kvkNummer":"69599084","vestigingsnummer":"000038509520","naam":"Test EMZ Nevenvestiging Govert","adres":{"binnenlandsAdres":{"type":"bezoekadres","straatnaam":"Geneinde","plaats":"Maastricht"}},
"type":"nevenvestiging","links":[{"rel":"basisprofiel","href":"https://api.kvk.nl/test/api/v1/basisprofielen/69599084"},{"rel":"vestigingsprofiel",
"href":"https://api.kvk.nl/test/api/v1/vestigingsprofielen/000038509520"}]},{"kvkNummer":"68750110","naam":"Test BV Donald","type":"rechtspersoon",
"links":[{"rel":"basisprofiel","href":"https://api.kvk.nl/test/api/v1/basisprofielen/68750110"}]},
{"kvkNummer":"69599068","naam":"Test Stichting Bolderbast",
"adres":{"binnenlandsAdres":{"type":"bezoekadres","straatnaam":"Oosterwal","plaats":"Lochem"}},"type":"rechtspersoon","links":[{"rel":"basisprofiel","href":"https://api.kvk.nl/test/api/v1/basisprofielen/69599068"}]},{"kvkNummer":"68750110","vestigingsnummer":"000037178598","naam":"Test BV Donald","adres":{"binnenlandsAdres":{"type":"bezoekadres","straatnaam":"Hizzaarderlaan","plaats":"Lollum"}},"type":"hoofdvestiging","links":[{"rel":"basisprofiel","href":"https://api.kvk.nl/test/api/v1/basisprofielen/68750110"},{"rel":"vestigingsprofiel","href":"https://api.kvk.nl/test/api/v1/vestigingsprofielen/000037178598"}]},{"kvkNummer":"69599076","vestigingsnummer":"000038509474","naam":"Test VOF Guus","adres":{"binnenlandsAdres":{"type":"bezoekadres","straatnaam":"Benny Goodmanstraat","plaats":"Almere"}},"type":"hoofdvestiging","links":[{"rel":"basisprofiel","href":"https://api.kvk.nl/test/api/v1/basisprofielen/69599076"},{"rel":"vestigingsprofiel","href":"https://api.kvk.nl/test/api/v1/vestigingsprofielen/000038509474"}]},{"kvkNummer":"68727720","naam":"Test NV Katrien - Statutory Naam","type":"rechtspersoon","links":[{"rel":"basisprofiel","href":"https://api.kvk.nl/test/api/v1/basisprofielen/68727720"}]},{"kvkNummer":"69599084","vestigingsnummer":"000038509504","naam":"Test EMZ Dagobert","adres":{"binnenlandsAdres":{"type":"bezoekadres","straatnaam":"Abebe Bikilalaan","plaats":"Amsterdam"}},"type":"hoofdvestiging","links":[{"rel":"basisprofiel","href":"https://api.kvk.nl/test/api/v1/basisprofielen/69599084"},{"rel":"vestigingsprofiel","href":"https://api.kvk.nl/test/api/v1/vestigingsprofielen/000038509504"}]},{"kvkNummer":"68727720","vestigingsnummer":"000037143557","naam":"Test NV Katrien - Handelsnaam","adres":{"binnenlandsAdres":{"type":"bezoekadres","straatnaam":"Rietdekkershof","plaats":"Veendam"}},"type":"hoofdvestiging","links":[{"rel":"basisprofiel","href":"https://api.kvk.nl/test/api/v1/basisprofielen/68727720"},{"rel":"vestigingsprofiel","href":"https://api.kvk.nl/test/api/v1/vestigingsprofielen/000037143557"}]}],
"links":[{"rel":"self","href":"https://api.kvk.nl/test/api/v2/zoeken?naam=test&pagina=1&resultatenperpagina=10"}]}